[package]
name = "synacor-challenge"
version = "0.1.0"
authors = ["tatref <tatref@github.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
regex = "1"
rustyline = "12"
clap = "4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.2.0"
serde_json = "1.0.105"
